name: mounted_state
description: Easily check if a widget is mounted before calling setState.
version: 1.0.0
repository: https://github.com/vixez/mounted_state

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: